sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm i -g now@canary
  - npm run build
  - npm run deploy

after_script: 
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev; fi 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - npm run cleanup

env:
  global:
    secure: pRD8SY8sxSvYadrKlEjwFh4FKIegXAMRIdHjcj9B/DeLfXfC+MEnOjKYeAD+NGniw1DRs7sjMyf89+2QMclKrrxWZj3+16LkHzCW1OwvYW14Le4/lnoxLiMm6DRGnJBHCyTZ25bwccjEWu7IqXxks0OA549TzwiAxQyqe8NXy3vSgrXHP+aiD5AXnojoxf4FrRoPL06tyHREhEJdiHQCygG17Uv1O33cPHIN1pmDFNZ1uvSef9QAf9X5UEH2nGGmw+19bdOppZKAQHql000WmABwjFgOSMH44NrzxCd6aT5VFYSNlFT2E3nxEh2pd96NMYvxPFtM1xJWbW2OIAa96RhwEDhnnYHcHTF1bsdt64ieJAu41HNMy2DZ+bL6o9zH8jwHipwZv+T0unEF30vzIrb8agB4RlI8rLuIS3jq2YNg4o4FUsdw9D5F4TMZcHPXr3o8qheNj2DR9zYsNNJplcANQmDtio0FKctsg6vsAZ6s0I2gWaCMIgtAfRoedgSwmXfo305150WGWTDuDOmOmxXG3UhccJA61m7CvMxYRBf6Ts3iKmYW/M/4k0YY8RIejcswgqUFoyNCJvJ6zKASodfOfP6nf0AXLkIIt3E6xvqNQKLyU4IZaKYjNgRvpHwae+k3X084mEHnanzvlf3oPYVXrh47eF7HAvwx6llO9jM=
